global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: connect-integration-qualtrak
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  amazonconnect:
   parameter_input: evaluate-amazonconnect-json.json
   template_file: evaluate-amazonconnect-json.template
  evaluate-json:
   parameter_input: evaluate-json.json
   template_file: evaluate-json.template
  evaluate-json-master:
   parameter_input: evaluate-json-master.json
   template_file: evaluate-json-master.template    
  evaluate-datastreaming-json-master:
    parameter_input: evaluate-datastreaming-json-master.json
    template_file: evaluate-datastreaming-json-master.template    
